// const shouldRenew = confirm('Бажаєте продовжити підписку');
// console.log(shouldRenew);
// let quantity = prompt('Введіть текст');
// console.log(quantity);
// quantity = Number(quantity);
// console.log(typeof quantity);
const str = 'Привіт';
console.log(str);
console.log(typeof str);
const num = 123;
console.log(num);
console.log(typeof num);
const flag = true;
console.log(flag);
console.log(typeof flag);
const txt = 'true';
console.log(txt);
console.log(typeof txt);
const quantity = prompt("Ім'я користувача");
console.log(quantity);
let atest = prompt('Якого року був початок Першої світової війни?');
console.log(atest);
let btest = prompt("Якого року відбулася Галицька битва?");
console.log(btest);
let ctest = prompt("Якого року відбувся Горлицький прорив?");
console.log(ctest);
let dtest = prompt("Якого року відбулася битва на горі Маківка?");
console.log(dtest);
let etest = prompt("Де і якого року відбулося створення ЗУР?");
console.log(etest); 